### ISSUE TITLE
Events Calendar: (semi) automated import of new events 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/wordpress#5]
**Content editor story**: 
1.  New events are uploaded via https://www.mmmnmnm.com/submit-new-event/ 
2. New event arrives at WordPress as Feedback
3. Content editor (MMN staff) manually creates new events for calendar: https://www.mmmnmnm.com/events/

**Enhancement**: add more automation to the process

**Challange**: https://theeventscalendar.com/important-facebook-api-changes/

**Comment by pvj** [comment]
Hi there, 

I can try working on improving this.

**Comment by gammaw** [comment]
Done via this https://github.com/mmmnmnm/wordpress/issues/23
